name: Test Workflow

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run maven test
        run: mvn clean test

  pull_request:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          pr_title: "feat: ${GITHUB_REF##*/}"
          pr_reviewer: "ACompleteNoobSmoke"
          pr_draft: true