#name: Response On Issues
#
#on:
#    issues:
#        types:
#        - opened
#        - closed
#
#
#jobs:
#    print-info:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Info
#          run: echo "${{ toJSON(github.event.issue) }}"
#
#    response_to_issues:
#        runs-on: ubuntu-latest
#        steps:
#        - name: Create Response
#          if: ${{ github.event.issue.state == 'open' }}
#          uses: EddieHubCommunity/gh-action-community/src/welcome@main
#          with:
#              github-token: ${{ secrets.GITHUB_TOKEN }}
#              issue-message: "It's great to have your input on this project."
#              footer: "Stay BASED!"
#
#    response_to_closed_issues:
#        runs-on: ubuntu-latest
#        steps:
#            - name: Create Closing Response
#              if: ${{ github.event.issue.state == 'closed' }}
#              uses: aws-actions/closed-issue-message@v1
#              with:
#                  repo-token: ${{ secrets.GITHUB_TOKEN }}
#                  message: "Great. It seems like the issue has been resolved. BASED GOD OUT!!"
#
