name: Testing Outputs

on:
  [push, issues]


jobs:
  getOutputs:
    runs-on: ubuntu-latest
    outputs:
      actionvalue: ${{ steps.action_value.outputs.action }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print
        run: echo "${{ toJSON(github) }}"
      - name: Get values
        id: action_value
        run: echo "action=${{ github.event_name }}" >> "$GITHUB_OUTPUT"


  printOutputs:
    runs-on: ubuntu-latest
    needs: getOutputs
    steps:
      - name: Push Print
        env:
          action: ${{ needs.getOutputs.outputs.actionvalue }}
        if: action == 'push'
        run: echo "I'm pushing P"

      - name: Issue Print
        env:
          action: ${{ needs.getOutputs.outputs.actionvalue }}
        if: action == 'issues'
        run: echo "You got trust issues"

