name: Practice Workflow

on:
    workflow_dispatch:

jobs:
    github-output:
        name: GitHub Outputs
        runs-on: ubuntu-latest
        steps:
            - name: Addition
              id: addition
              run: |
                echo "Answer=$((2 + 2))" >> $GITHUB_OUTPUT
                echo "Name=Navid" >> $GITHUB_OUTPUT

            - name: Answer
              run: |
               echo ${{steps.addition.outputs.Answer}}
               echo "${{steps.addition.outputs.Name}} Is The Greatest Programmer Eva!" >> sample.txt

            - 
              uses: actions/upload-artifact@v4
              with:
                 name: my_new_artifact
                 path: sample.txt

    github-output-2:
        name: GitHub Output 2
        runs-on: macos-latest
        needs: github-output
        steps:
            - name: Existing Outputs
              run: echo ${{steps.addition.outputs.Name}}
