name: Practice Workflow
 
on:
    push:


jobs:
    hello-world:
        name: Hello World
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Java
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu' # See 'Supported distributions' for available options
                java-version: '21'

            - name: Build Java
              run: mvn clean install

            




